//Header file for local constants

#ifndef _WIRELESS_MONITOR_H_
#define _WIRELESS_MONITOR_H

#define SERIAL_PORT_PACKET_SIZE 6
#define MAX_NUM_TESTS	1
#define TIME_SCALE      (1000/5)
typedef enum WirelessMonitorStatus
{
	SERIAL_PORT_SUCCESS=0,
	SERIAL_PORT_UNINITIALIZED,
	SERIAL_PORT_WRITE_TIMEOUT,
	SERIAL_PORT_READTIMEOUT,
	SERIAL_PORT_INVALID_RESPONSE,
	SERIAL_PORT_NOT_DETECTED,
	SERIAL_PORT_AUTHORIZATION_ERROR,
	SERIAL_PORT_INVALID_NAME_ERROR,
	SERIAL_PORT_ARGUMENT_ERROR,
	SERIAL_PORT_IO_ERROR,
	SERIAL_PORT_ALREADY_OPEN_ERROR,
	SERIAL_PORT_SYNC_LOST,
};


#endif
